include $(SFMT_ROOT)/mk/sfmt.x86_64.native.linux.gcc.mk
include $(SFMT_ROOT)/mk/sfmt.cpuflags.mk

CFLAGS := $(CPU_CFLAGS) $(EXECENV_CFLAGS) $(TOOLCHAIN_CFLAGS) $(MACHINE_CFLAGS)
CFLAGS += $(TARGET_CFLAGS) 
LDFLAGS := $(CPU_LDFLAGS) $(EXECENV_LDFLAGS) $(TOOLCHAIN_LDFLAGS) $(MACHINE_LDFLAGS)
LDFLAGS += $(TARGET_LDFLAGS)

CFLAGS += $(OPTIMIZE_FLAGS) $(WERROR_FLAGS)

export CFLAGS
export LDFLAGS

